-- Import 2023 deceased data
-- Auto-generated from Excel

INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    1,
    'الحاج قاسم حسن المعلم ابوخالد',
    'حاج قاسم حسن معلم ابوخالد',
    'ذكر',
    85,
    'الاربعاء',
    '11\6\1444',
    '4\1\2023',
    'أ',
    1,
    1,
    'أ-1-1',
    26.649576,
    49.958884,
    'خالد قاسم المعلم ',
    'ابنه',
    598483405,
    '4400042335'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    2,
    'الشاب فتح رضي ال خلف',
    'شاب فتح رضي خلف',
    'ذكر',
    42,
    'الاثنين',
    '16\6\1444',
    '9\1\2023',
    'أ',
    1,
    2,
    'أ-1-2',
    26.64958,
    49.958905,
    'نجيب رضي ال خلف',
    'اخ',
    543775995,
    '4400043349'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    3,
    'الشاب ياسر محمد الفريد',
    'شاب ياسر محمد فريد',
    'ذكر',
    29,
    'الخميس',
    '19\6\1444',
    '12\1\2023',
    'أ',
    1,
    3,
    'أ-1-3',
    26.649584,
    49.958925,
    'حكيم حبيب الفريد',
    'عمته',
    505853514,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    4,
    'الشابه فاطمه حبيب الصادق',
    'شابه فاطمه حبيب صادق',
    'انثى',
    45,
    'الاحد',
    '22\6\1444',
    '15\1\2023',
    'أ',
    1,
    4,
    'أ-1-4',
    26.649588,
    49.958946,
    'مفيد علي عباس ال حميد',
    'زوجها',
    505903653,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    5,
    'الشاب علي زكي عجاج',
    'شاب علي زكي عجاج',
    'ذكر',
    19,
    'الاحد',
    '22\6\1444',
    '15\1\2023',
    'أ',
    1,
    5,
    'أ-1-5',
    26.649592,
    49.958967,
    'زكي عبدالمحسن عجاج',
    'ابنه',
    542744352,
    '4400045179'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    6,
    'الحاج عبدالرزاق حسين حميد',
    'حاج عبدالرزاق حسين حميد',
    'ذكر',
    68,
    'الثلاثاء',
    '24\6\1444',
    '17\1\2023',
    'أ',
    1,
    6,
    'أ-1-6',
    26.649596,
    49.958987,
    'جواد عبدالرزاق حميد',
    'ابنه',
    531817535,
    '4400045843'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    7,
    'الحاج علي حسين الحساوي',
    'حاج علي حسين حساوي',
    'ذكر',
    83,
    'الثلاثاء',
    '24\6\1444',
    '17\1\2023',
    'أ',
    1,
    7,
    'أ-1-7',
    26.6496,
    49.959008,
    'عبدالله علي الحساي ',
    'ابنه',
    558886504,
    '4400046003'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    8,
    'الشاب كامل عبدالله الصادق',
    'شاب كامل عبدالله صادق',
    'ذكر',
    48,
    'الثلاثاء',
    '24\6\1444',
    '17\1\2023',
    'أ',
    1,
    8,
    'أ-1-8',
    26.649604,
    49.959029,
    'علي عبدالله الصادق',
    'اخ',
    504984921,
    '440004091'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    9,
    'الشاب ياسر محمد غلاب',
    'شاب ياسر محمد غلاب',
    'ذكر',
    48,
    'السبت',
    '28\6\1444',
    '21\1\2023',
    'أ',
    1,
    9,
    'أ-1-9',
    26.649608,
    49.959049,
    'عبدالله عيسى العيسى ',
    'خاله',
    545174011,
    '44000046946'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    10,
    'الحاجة مريم حسين مرهون (المختار)',
    'حاجه مريم حسين مرهون (مختار)',
    'انثى',
    99,
    'الاثنين',
    '1\7\14444',
    '23\1\2023',
    'أ',
    1,
    10,
    'أ-1-10',
    26.649611,
    49.95907,
    'حبيب صالح خزعل',
    'جدته',
    561147994,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    11,
    'الحاج محمد احمد ال دخيل',
    'حاج محمد احمد دخيل',
    'ذكر',
    62,
    'الخميس',
    '4\7\1444',
    '26\1\2023',
    'أ',
    1,
    11,
    'أ-1-11',
    26.649615,
    49.959091,
    'قاسم محمد ال ابراهيم',
    'بن عمته',
    503950230,
    '4400048477'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    12,
    'الحاجه صالحه مكي ال خميس',
    'حاجه صالحه مكي خميس',
    'انثى',
    69,
    'الخميس',
    '4\7\1444',
    '26\1\2023',
    'أ',
    1,
    12,
    'أ-1-12',
    26.649619,
    49.959112,
    'عبدالعظيم مكي الخويلدي',
    'زوجها',
    506849372,
    '4400048693'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    13,
    'الشاب حسين علي  ال جعفر',
    'شاب حسين علي جعفر',
    'ذكر',
    32,
    'الاحد',
    '7\7\1444',
    '29\1\2023',
    'أ',
    1,
    13,
    'أ-1-13',
    26.649623,
    49.959132,
    'محمد علي عبدالله ال جعفر',
    'اخ',
    559594644,
    '44000049374'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    14,
    'الشاب محمد عبدالله ال عيسى',
    'شاب محمد عبدالله عيسي',
    'ذكر',
    24,
    'الاربعاء',
    '10\7\1444',
    '1\2\2023',
    'أ',
    1,
    14,
    'أ-1-14',
    26.649627,
    49.959153,
    'مكي علي ال عيسى',
    'عمه',
    555851535,
    '4400050519'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    15,
    'الحاج حسين علي محمد رهين',
    'حاج حسين علي محمد رهين',
    'ذكر',
    64,
    'الجمعة',
    '12\7\1444',
    '3\2\2023',
    'أ',
    1,
    15,
    'أ-1-15',
    26.649631,
    49.959174,
    'علي محمد علي رهين',
    'ابن اخ',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    16,
    'الحاج محمد علي ال محمد',
    'حاج محمد علي محمد',
    'ذكر',
    72,
    'الاحد',
    '14\7\1444',
    '5\2\2023',
    'أ',
    1,
    16,
    'أ-1-16',
    26.649635,
    49.959194,
    'اخضير علي مهدي ال محمد ',
    'اخ',
    506806342,
    '4400051523'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    17,
    'الحاجه مريم احمد ال ليل',
    'حاجه مريم احمد ليل',
    'انثى',
    96,
    'الجمعة',
    '26\7\1444',
    '17\2\2023',
    'أ',
    1,
    17,
    'أ-1-17',
    26.649639,
    49.959215,
    'محمد الصفواني ',
    'ابنها',
    503852951,
    '400054798'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    18,
    'الحاجة فاطمه علي مهدي اداؤود',
    'حاجه فاطمه علي مهدي اداوود',
    'انثى',
    77,
    'الثلاثاء',
    '1\8\1444',
    '21\2\2023',
    'أ',
    2,
    18,
    'أ-2-18',
    NULL,
    NULL,
    'علي حسن الموسى',
    'ابنها',
    504487381,
    '4400056065'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    19,
    'الحاج حسن علي المرهون',
    'حاج حسن علي مرهون',
    'ذكر',
    92,
    'الخميس',
    '3\8\1444',
    '23\2\2023',
    'أ ',
    2,
    19,
    'أ-2-19',
    NULL,
    NULL,
    'محمد حسن المرهون',
    'اخ',
    505906514,
    '4400056444'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    20,
    'الحاج سمير قاسم العوض',
    'حاج سمير قاسم عوض',
    'ذكر',
    59,
    'الاحد',
    '13\8\1444',
    '5\3\2023',
    'أ',
    2,
    20,
    'أ-2-20',
    NULL,
    NULL,
    'رضا محمد الحنابي ',
    'زوج اخته',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    21,
    'الحاج حسين صالح عبدالله المغلق',
    'حاج حسين صالح عبدالله مغلق',
    'ذكر',
    69,
    'الاثنين',
    '14\8\1444',
    '6\3\2023',
    'أ',
    2,
    21,
    'أ-2-21',
    NULL,
    NULL,
    'محمد صالح المغلق',
    'اخ',
    503890899,
    '4400059506'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    22,
    'الحاج حسين علي الحضري',
    'حاج حسين علي حضري',
    'ذكر',
    77,
    'الاربعاء',
    '16\8\1444',
    '8\3\2023',
    'أ',
    2,
    22,
    'أ-2-22',
    NULL,
    NULL,
    'فيصل حسين احضري',
    'ابن ',
    558200377,
    '4400060211'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    23,
    'الحاج سعيد محمد احمد الفارس',
    'حاج سعيد محمد احمد فارس',
    'ذكر',
    NULL,
    'الخميس',
    '17\8\1444',
    '9\3\2023',
    'أ',
    2,
    23,
    'أ-2-23',
    NULL,
    NULL,
    'فراس سعيد الفارس ',
    'ابن ',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    24,
    'الحاج علي مكي ال خميس',
    'حاج علي مكي خميس',
    'ذكر',
    86,
    'الجمعه',
    '18\8\1444',
    '10\3\2023',
    'أ',
    2,
    24,
    'أ-2-24',
    NULL,
    NULL,
    'حسين علي مكي ال خميس',
    'ابن ',
    547126869,
    '4400061128'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    25,
    'الحاجه صالحه محمد الصادق',
    'حاجه صالحه محمد صادق',
    'انثى',
    100,
    'السبت',
    '19\8\1444',
    '11\3\2023',
    'أ',
    2,
    25,
    'أ-2-25',
    NULL,
    NULL,
    'جابر عبدالله ال حمدان',
    'ابن ',
    503852411,
    '440006952'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    26,
    'الحاجة زهراء حسن احمد ال داؤود',
    'حاجه زهراء حسن احمد داوود',
    'انثى',
    NULL,
    'الثلاثاء',
    '22\8\1444',
    '14\3\2023',
    'أ',
    2,
    26,
    'أ-2-26',
    NULL,
    NULL,
    'محمد حسن احمد ال داؤود',
    'اخ',
    ' ',
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    27,
    'الشابه بتول علي حسين الصادق',
    'شابه بتول علي حسين صادق',
    'انثى',
    28,
    'الجمعه',
    NULL,
    '17\3\2023',
    'أ',
    2,
    27,
    'أ-2-27',
    NULL,
    NULL,
    'صادق علي حسين الصادق',
    'اخ',
    505184295,
    '44356432'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    28,
    'الحاج علي جاسم سلمان الصفواني',
    'حاج علي جاسم سلمان صفواني',
    'ذكر',
    92,
    'السبت',
    '26\8\1444',
    '18\3\2023',
    'أ',
    2,
    28,
    'أ-2-28',
    NULL,
    NULL,
    'احمد علي جاسم الصفواني ',
    'ابن ',
    552096392,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    29,
    'الحاجة خاتون حسين اسعد الساده',
    'حاجه خاتون حسين اسعد ساده',
    'انثى',
    91,
    'السبت',
    '26\8\1444',
    '18\3\2023',
    'أ',
    2,
    29,
    'أ-2-29',
    NULL,
    NULL,
    'محمد علي علوي الساده',
    'ابن ',
    503818526,
    '4400062812'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    30,
    'الحاجة فاطمة احمد حسن ال سعيد',
    'حاجه فاطمه احمد حسن سعيد',
    'انثى',
    61,
    'الاثنين',
    '28\2\1444',
    '20\3\2023',
    'أ',
    2,
    30,
    'أ-2-30',
    NULL,
    NULL,
    'محمد علي صالح ال اسعيد ',
    'ابن ',
    533189652,
    '4400063466'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    31,
    'محمد علوي هاشم الساده',
    'محمد علوي هاشم ساده',
    'ذكر',
    76,
    'الاربعاء',
    '30\8\1444',
    '22\3\2023',
    'أ',
    2,
    31,
    'أ-2-31',
    NULL,
    NULL,
    'علاء محمد هاشم العلوي',
    'ابن ',
    504801422,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    32,
    'الشابة دعاء حسن احمد عجاج',
    'شابه دعاء حسن احمد عجاج',
    'انثى',
    32,
    'الاحد',
    '4\9\1444',
    '26\3\2023',
    'أ',
    2,
    32,
    'أ-2-32',
    NULL,
    NULL,
    'عبدالله علي عبدالله ال عيسى',
    'زوجها',
    555826742,
    '4400064881'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    33,
    'الحاجة سميرة سلمان محمد الحنابي',
    'حاجه سميره سلمان محمد حنابي',
    'انثى',
    61,
    'الخميس',
    '8\9\1444',
    '30\3\2023',
    'أ',
    2,
    33,
    'أ-2-33',
    NULL,
    NULL,
    'سعيد عبدالله ابراهيم الحنابي',
    'اخو زوجها',
    506884801,
    '4400065991'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    34,
    'الحاج محمد علي محمد ال داؤود',
    'حاج محمد علي محمد داوود',
    'ذكر',
    80,
    'الاحد',
    '11\9\1444',
    '2\4\2023',
    'أ',
    2,
    34,
    'أ-2-34',
    NULL,
    NULL,
    'علي محمد ال داؤود',
    'ابن ',
    558977244,
    '4400066637'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    35,
    'الحاج محمد حسن علي الناصر',
    'حاج محمد حسن علي ناصر',
    'ذكر',
    71,
    'الاثنين',
    '12\9\1444',
    '3\4\2023',
    'أ',
    3,
    35,
    'أ-3-35',
    NULL,
    NULL,
    'علي محمد حسن الناصر',
    'ابن',
    534433222,
    '4400066911'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    36,
    'الحاجة خضرة علي محمد الحنابي',
    'حاجه خضره علي محمد حنابي',
    'انثى',
    61,
    'الاثنين',
    '19\9\1444',
    '10\4\2023',
    'أ',
    3,
    36,
    'أ-3-36',
    NULL,
    NULL,
    'محمد جلال محمد ال شاهين',
    'ابن',
    566380613,
    '4400068966'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    37,
    'الحاجة اية علي حسن غلاب',
    'حاجه ايه علي حسن غلاب',
    'انثى',
    60,
    'الثلاثاء',
    '20\9\1444',
    '11\4\2023',
    'أ',
    3,
    37,
    'أ-3-37',
    NULL,
    NULL,
    'احمد علي حسن غلاب',
    'اخ',
    505804774,
    '4400069258'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    38,
    'علوي هاشم اسعد ال حسن',
    'علوي هاشم اسعد حسن',
    'ذكر',
    80,
    'الاربعاء',
    '21\9\1444',
    '12\4\2023',
    'أ',
    3,
    38,
    'أ-3-38',
    NULL,
    NULL,
    'محمد علوي هاشم ال حسن ',
    'ابن',
    504817812,
    '4400069428'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    39,
    'شوق عصام عبدالكريم ال درويش',
    'شوق عصام عبدالكريم درويش',
    'انثى',
    21,
    'الخميس',
    '22\9\1444',
    '13\4\2023',
    'أ',
    3,
    39,
    'أ-3-39',
    NULL,
    NULL,
    'فاطمة موسى جعفر الصادق',
    'ام',
    567792374,
    '4400069830'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    40,
    'الشاب محمد فادي عبدالله ال ابراهيم',
    'شاب محمد فادي عبدالله ابراهيم',
    'ذكر',
    14,
    'الاثنين',
    '26\9\14444',
    '17\4\2023',
    'أ',
    3,
    40,
    'أ-3-40',
    NULL,
    NULL,
    'عادل احمد علي ال ابراهيم',
    'عم',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    41,
    'رباب محمد علي الصادق',
    'رباب محمد علي صادق',
    'انثى',
    63,
    'الخميس',
    '29\9\1444',
    '20\4\2023',
    'أ',
    3,
    41,
    'أ-3-41',
    NULL,
    NULL,
    'منير محمد علي الصادق',
    'اخ',
    540444297,
    '4400071431'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    42,
    'علي عبدالله علي ال داؤود',
    'علي عبدالله علي داوود',
    'ذكر',
    72,
    'الاثنين',
    '4\10\1444',
    '24\4\2023',
    'أ',
    3,
    42,
    'أ-3-42',
    NULL,
    NULL,
    'محمد علي عبدالله ال داؤود',
    'ابن',
    543835090,
    '53357'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    43,
    'حبيب وهب مهدي الخليفه',
    'حبيب وهب مهدي خليفه',
    'ذكر',
    58,
    'الاربعاء',
    '6\10\1444',
    '26\4\2023',
    'أ',
    3,
    43,
    'أ-3-43',
    NULL,
    NULL,
    'علي حبيب وهب الخليفه',
    'ابن',
    564757805,
    '4400072925'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    44,
    'مليكه محمد محمد ال قريش',
    'مليكه محمد محمد قريش',
    'انثى',
    73,
    'السيت',
    '9\10\1444',
    '29\4\2023',
    'أ',
    3,
    44,
    'أ-3-44',
    NULL,
    NULL,
    'جميل عبدالواحد المعيني',
    'ابن',
    553629923,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    45,
    'ابراهيم احمد اسعد الساده',
    'ابراهيم احمد اسعد ساده',
    'ذكر',
    77,
    'الاحد',
    '10\10\1444',
    '30\4\2023',
    'أ',
    3,
    45,
    'أ-3-45',
    NULL,
    NULL,
    'زكريا ابراهيم احمد الساده',
    'ابن',
    548386923,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    46,
    'علي محمد علي ال ناصر',
    'علي محمد علي ناصر',
    'ذكر',
    NULL,
    'الاحد',
    '10\10\1444',
    '30\4\2023',
    'أ',
    3,
    46,
    'أ-3-46',
    NULL,
    NULL,
    'حسين علي محمد ال ناصر',
    'ابن',
    505905714,
    '4400073963'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    47,
    'سيف عبدالمطلب عل ال سيف',
    'سيف عبدالمطلب عل سيف',
    'ذكر',
    53,
    'الاحد',
    '10\10\1444',
    '30\4\2023',
    'أ',
    3,
    47,
    'أ-3-47',
    NULL,
    NULL,
    'فراس سلمان محمد ال حبيب',
    'ابن عمته',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    48,
    'علي احمد صالح ال ابراهيم',
    'علي احمد صالح ابراهيم',
    'ذكر',
    30,
    'السبت',
    '16\10\1444',
    '6\5\2023',
    'أ',
    3,
    48,
    'أ-3-48',
    NULL,
    NULL,
    'علي صالح علي ال ابراهيم',
    'عم',
    503841862,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    49,
    'عبدة العلي علي عيسى المحسن',
    'عبده علي علي عيسي محسن',
    'انثى',
    97,
    'الاثنين',
    '18\10\1444',
    '8\5\2023',
    'أ',
    3,
    19,
    'أ-3-49',
    NULL,
    NULL,
    'سمير عبدالله محمد ال درويش',
    'ابن',
    503883068,
    '4400076606'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    50,
    'نجاة عبدالله حبيب ال مرهون',
    'نجاه عبدالله حبيب مرهون',
    'انثى',
    49,
    'الثلاثاء',
    '19\10\1444',
    '9\5\2023',
    'أ',
    3,
    50,
    'أ-3-50',
    NULL,
    NULL,
    'ياسر علي حميد قريش ',
    'زوج',
    ' ',
    '4400076897'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    51,
    'معصومة صالح علي ال عباس',
    'معصومه صالح علي عباس',
    'انثى',
    84,
    'السبت ',
    '23\10\1444',
    '13\5\2023',
    'أ',
    3,
    51,
    'أ-3-51',
    NULL,
    NULL,
    'محمد سعيد علي ال حمدان',
    'حفيد',
    556061561,
    '4400078084'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    52,
    'عفيفة علي حسين الزين',
    'عفيفه علي حسين زين',
    'انثى',
    91,
    'الاثنين',
    '25\10\1444',
    '15\5\2023',
    'أ',
    4,
    52,
    'أ-4-52',
    NULL,
    NULL,
    'احمد علي احمد المرهون',
    'ابن',
    505829569,
    '4400078366'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    53,
    'عبدالرزاق عبدالوهاب ال كاظم',
    'عبدالرزاق عبدالوهاب كاظم',
    'ذكر',
    81,
    'الاثنين',
    '25\10\1444',
    '15\5\2023',
    'أ',
    4,
    53,
    'أ-4-53',
    NULL,
    NULL,
    'قسم عبدالوهاب ال كاظم',
    'اخ',
    554992647,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    54,
    'فاطمة علي يحيى ال دخيل',
    'فاطمه علي يحيي دخيل',
    'انثى',
    75,
    'الاثنين',
    '25\10\1444',
    '15\5\2023',
    'أ',
    4,
    54,
    'أ-4-54',
    NULL,
    NULL,
    'وجيه حسن علي ال غلاب',
    'ابن',
    557101033,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    55,
    'فاطمة عبدالله محمد اليوسف',
    'فاطمه عبدالله محمد يوسف',
    'انثى',
    91,
    'الاربعاء',
    '27\10\1444',
    '17\5\2023',
    'أ',
    4,
    55,
    'أ-4-55',
    NULL,
    NULL,
    'عمارمحمد هاشم الصفواني',
    'حفيد',
    551377893,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    56,
    'نجيبة حسين صالح ال حسين ام خالد',
    'نجيبه حسين صالح حسين ام خالد',
    'انثى',
    NULL,
    'السبت ',
    '30\10\1444',
    '20\5\2023',
    'أ',
    4,
    56,
    'أ-4-56',
    NULL,
    NULL,
    'هاشم علوي هاشم ال حسين',
    'ابن',
    500665619,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    57,
    'حسين حبيب محمد فاران',
    'حسين حبيب محمد فاران',
    'ذكر',
    75,
    'الثلاثاء',
    '10\11\1444',
    '30\5\2023',
    'أ',
    4,
    57,
    'أ-4-57',
    NULL,
    NULL,
    'خالد حسين فاران',
    'ابن',
    506805597,
    '4400082238'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    58,
    'حبيب عبدالكريم محمد ال درويش',
    'حبيب عبدالكريم محمد درويش',
    'ذكر',
    68,
    'الاحد',
    '15\11\1444',
    '4\6\2023',
    'أ',
    4,
    58,
    'أ-4-58',
    NULL,
    NULL,
    'حسين عبدرب الرسول العيسى ',
    'زوج ابنته',
    569983392,
    '4400083370'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    59,
    'ساجدة حبيب احمد ال قريش',
    'ساجده حبيب احمد قريش',
    'انثى',
    37,
    'الاثنين',
    '16\11\14444',
    '5\6\2023',
    'أ',
    4,
    59,
    'أ-4-59',
    NULL,
    NULL,
    'مهدي حسين احمد ال قريش',
    'زوجها',
    532855522,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    60,
    'علي احمد صالح المرهون',
    'علي احمد صالح مرهون',
    'ذكر',
    92,
    'الاثنين',
    '16\11\14444',
    '5\6\2023',
    'أ',
    4,
    60,
    'أ-4-60',
    NULL,
    NULL,
    'عبدالله علي المرهون',
    'ابن',
    504417991,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    61,
    'احمد حسين علي المرهون',
    'احمد حسين علي مرهون',
    'ذكر',
    17,
    'الاربعاء',
    '18\11\1444',
    '7\6\2023',
    'أ',
    4,
    61,
    'أ-4-61',
    NULL,
    NULL,
    'عبدالله علي ال عيسى',
    NULL,
    504831159,
    '4400084419'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    62,
    'حسين محمد علي الحجي',
    'حسين محمد علي حجي',
    'ذكر',
    86,
    'الجمعه',
    '20\11\1444',
    '9\6\2023',
    'أ',
    4,
    62,
    'أ-4-62',
    NULL,
    NULL,
    'هاشم حسن علي القويعي ',
    'زوج خالته',
    564488883,
    '4400084799'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    63,
    'سلوى حسين حسن ال حميد',
    'سلوي حسين حسن حميد',
    'انثى',
    60,
    'السبت',
    '21\11\1444',
    '10\6\2023',
    'أ',
    4,
    63,
    'أ-4-62',
    NULL,
    NULL,
    'عبدالله علي صالح المطيلق',
    'ابن',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    64,
    'سعيد حسين حسن السعيد',
    'سعيد حسين حسن سعيد',
    'ذكر',
    60,
    'الخميس',
    '26\11\1444',
    '15\6\2023',
    'أ',
    4,
    64,
    'أ-4-64',
    NULL,
    NULL,
    'محمد حسين حسن السعيد',
    'اخ',
    560500247,
    '4400086384'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    65,
    'صغراء احمد علي ال داؤود',
    'صغراء احمد علي داوود',
    'انثى',
    64,
    'الجمعه',
    '27\11\1444',
    '16\6\2023',
    'أ',
    4,
    65,
    'أ-4-65',
    NULL,
    NULL,
    'علي حسن حسين ال اسعد',
    'زوجها',
    505820109,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    66,
    'عبدالله حسن عبدالحميدالداؤود',
    'عبدالله حسن عبدالحميدالداوود',
    'ذكر',
    81,
    'الاثنين',
    '1\12\1444',
    '19\6\2023',
    'أ',
    4,
    66,
    'أ-4-66',
    NULL,
    NULL,
    'عبدالمنعم عبدالله الداؤود',
    'ابن',
    503815088,
    '4400087284'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    67,
    'زينب عبدالله علي ال مبارك',
    'زينب عبدالله علي مبارك',
    'انثى',
    43,
    'الاربعاء',
    '3\12\1444',
    '21\6\2023',
    'أ',
    4,
    67,
    'أ-4-67',
    NULL,
    NULL,
    'علي عبدالله علي ال مبارك',
    'اخ',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    68,
    'علي حسن الفريد',
    'علي حسن فريد',
    'ذكر',
    66,
    'الاربعاء',
    '3\12\1444',
    '21\6\2023',
    'أ',
    4,
    68,
    'أ-4-68',
    NULL,
    NULL,
    'طلال احمد ال سيف',
    'ابن اخت',
    502883383,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    69,
    'سعيد عبدالكريم محمد ال عيسى',
    'سعيد عبدالكريم محمد عيسي',
    'ذكر',
    71,
    'الجمعة',
    '5\12\1444',
    '23\6\2023',
    'أ',
    5,
    69,
    'أ-4-96',
    NULL,
    NULL,
    'عبدالرحيم عبدالكريم ال عيسى',
    'اخ',
    533599033,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    70,
    'علوية ناصر شرف ال شبر',
    'علويه ناصر شرف شبر',
    'انثى',
    86,
    'الاحد',
    '7\12\1444',
    '25\6\2023',
    'أ',
    5,
    70,
    'أ-5-70',
    NULL,
    NULL,
    'علي عدنان علي ال شبر',
    'ابن',
    505855735,
    '4400089171'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    71,
    'فاطمه محمد الحجي',
    'فاطمه محمد حجي',
    'انثى',
    92,
    'الاثنين',
    '8\12\1444',
    '26\6\2023',
    'أ',
    5,
    71,
    'أ-5-71',
    NULL,
    NULL,
    'حسين صالح المغلق',
    'ابن',
    NULL,
    '4400089247'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    72,
    'فاطمة علي محمد ال سيف',
    'فاطمه علي محمد سيف',
    'انثى',
    63,
    'الاثنين',
    '8\12\1444',
    '26\6\2023',
    'أ',
    5,
    72,
    'أ-5-72',
    NULL,
    NULL,
    'عبدالمحسن ال سيف',
    'زوج',
    505845799,
    '4400089320'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    73,
    'زهرة محمد عبدالرسول ال شعيب',
    'زهره محمد عبدالرسول شعيب',
    'انثى',
    73,
    'الاربعاء',
    '10\12\1444',
    '28\6\2023',
    'أ',
    5,
    73,
    'أ-5-73',
    NULL,
    NULL,
    'شبيب محمد عبالله شعيب',
    'عمه',
    503966476,
    '4400089718'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    74,
    'فاطمة محمد حسن ال مبارك',
    'فاطمه محمد حسن مبارك',
    'انثى',
    68,
    'الاربعاء',
    '10\12\1444',
    '28\6\2023',
    'أ',
    5,
    74,
    'أ-5-74',
    NULL,
    NULL,
    'حسن عبدالله مبارك ال مبارك',
    'والدته',
    503826643,
    '4400089803'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    75,
    'علي احمد عبدالله الشلاتي',
    'علي احمد عبدالله شلاتي',
    'ذكر',
    43,
    'السبت',
    '13\12\1444',
    '1\7\2023',
    'أ',
    5,
    75,
    'أ-5-75',
    NULL,
    NULL,
    'عبدالله احمد عبدالله الشلاتي ',
    'اخ',
    5000444850,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    76,
    'صالح حسن محمد الخزعل',
    'صالح حسن محمد خزعل',
    'ذكر',
    41,
    'الاثنين',
    '15\12\1444',
    '3\7\2023',
    'أ',
    5,
    76,
    'أ-5-76',
    NULL,
    NULL,
    'علي حسن الخزعل',
    'اخ',
    505912383,
    '4400091552'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    77,
    'محمد صالح محمد الشرياوي',
    'محمد صالح محمد شرياوي',
    'ذكر',
    92,
    'الثلاثاء',
    '16\12\1444',
    '4\7\2023',
    'أ',
    5,
    77,
    'أ-5-77',
    NULL,
    NULL,
    'احمد محمد صالح الشرياوي',
    'ابن',
    541809893,
    '4400091529'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    78,
    'زهراء سلمان علي ال غريب',
    'زهراء سلمان علي غريب',
    'انثى',
    71,
    'السبت ',
    '4\1\1445',
    '22\7\2023',
    'أ',
    5,
    78,
    'أ-5-78',
    NULL,
    NULL,
    'ياسر عبدالوهاب الحنابي ',
    'زوج بنتها',
    547327472,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    79,
    'علي حسن علي ال محمد',
    'علي حسن علي محمد',
    'ذكر',
    63,
    'السبت ',
    '11\1\1445',
    '29\7\2023',
    'أ',
    5,
    79,
    'أ-5-79',
    NULL,
    NULL,
    'هاشم حسن علي ال محمد',
    'ابن',
    505848931,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    80,
    'زهراء احمد ال مدن',
    'زهراء احمد مدن',
    'انثى',
    85,
    'السبت ',
    '11\1\1445',
    '29\7\2023',
    'أ',
    5,
    80,
    'أ-5-80',
    NULL,
    NULL,
    'عبدالله سعيد محمد الحايكي',
    'ابن',
    569887769,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    81,
    'علية علي العبدالله',
    'عليه علي عبدالله',
    'انثى',
    52,
    'الجمعة',
    '17\1\1445',
    '4\8\2023',
    'أ',
    5,
    81,
    'أ-5-81',
    NULL,
    NULL,
    'احمد محمد وهب ال قريش',
    'ابن',
    561906097,
    '4500004076'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    82,
    'رضية عبدالله رضي المزين',
    'رضيه عبدالله رضي مزين',
    'انثى',
    48,
    'الثلاثاء',
    '22\1\1445',
    '8\8\2023',
    'أ',
    5,
    82,
    'أ-5-82',
    NULL,
    NULL,
    'عصام عبدالله المزين',
    'اخ',
    548333908,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    83,
    'هاشم شرف احمد الساده',
    'هاشم شرف احمد ساده',
    'ذكر',
    61,
    'الاحد',
    '26\1\1445',
    '13\8\2023',
    'أ',
    5,
    83,
    'أ-5-83',
    NULL,
    NULL,
    'عدنان هاشم الساده',
    'ابن ',
    556888497,
    '4500006245'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    84,
    'دعاء باسم المعيني',
    'دعاء باسم معيني',
    'انثى',
    31,
    'الاثنين',
    '27\1\1445',
    '14\8\2023',
    'أ',
    5,
    84,
    'أ-5-84',
    NULL,
    NULL,
    'صالح محمد احمد المغلق',
    'ابن خالتها',
    509930070,
    '4500006379'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    85,
    'عبدالله احمد المسلم',
    'عبدالله احمد مسلم',
    'ذكر',
    66,
    'الأربعاء',
    '7\2\1445',
    '23\8\2023',
    'أ',
    5,
    85,
    'أ-5-85',
    NULL,
    NULL,
    'رجائي عبدالله المسلم',
    'ابن',
    509929788,
    '4500008737'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    86,
    'علي سعيد مهدي المحسن',
    'علي سعيد مهدي محسن',
    'ذكر',
    33,
    'الجمعة',
    '9\2\1445',
    '25\8\2023',
    'أ',
    6,
    86,
    'أ-6-86',
    NULL,
    NULL,
    'سعيد مهدي المحسن ',
    'اب',
    505890386,
    '45000092228'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    87,
    'رياحين احمد العوامي',
    'رياحين احمد عوامي',
    'انثى',
    41,
    'الجمعة',
    '9\2\1445',
    '25\8\2023',
    'أ',
    6,
    87,
    'أ-6-87',
    NULL,
    NULL,
    'رستم احمد العوامي',
    'اخ',
    506854551,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    88,
    'عبدالكريم سلمان العبدالحي',
    'عبدالكريم سلمان عبدالحي',
    'ذكر',
    58,
    'السبت ',
    '17\2\1445',
    '2\9\2023',
    'أ',
    6,
    88,
    'أ-6-88',
    NULL,
    NULL,
    'علي عبدالكريم العبدالحي',
    'ابن',
    NULL,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    89,
    'عبدالله سلمان ال فردان',
    'عبدالله سلمان فردان',
    'ذكر',
    78,
    'الخميس',
    '22\2\1445',
    '7\9\2023',
    'أ',
    6,
    89,
    'أ-6-89',
    NULL,
    NULL,
    'محمد عبدالكريم القلاف',
    'خاله',
    563217300,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    90,
    'جميل حسن القرين',
    'جميل حسن قرين',
    'ذكر',
    59,
    'الخميس',
    '22\2\1445',
    '7\9\2023',
    'أ',
    6,
    90,
    'أ-6-90',
    NULL,
    NULL,
    'يوسف حسين العالي',
    NULL,
    504958387,
    '4500013181'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    91,
    'يوسف ناصح احمد العجاج',
    'يوسف ناصح احمد عجاج',
    'ذكر',
    26,
    'السبت ',
    '24\2\1445',
    '9\9\2023',
    'أ',
    6,
    91,
    'أ-6-91',
    NULL,
    NULL,
    'فراس محمد ال حمدان',
    'ابن خاله',
    566456365,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    92,
    'حسن علي المرهون',
    'حسن علي مرهون',
    'ذكر',
    69,
    'الأربعاء',
    '28\2\1445',
    '13\9\2023',
    'أ',
    6,
    92,
    'أ-6-92',
    NULL,
    NULL,
    'باقر حسن المرهون',
    'ابن',
    541848119,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    93,
    'زكية حسن السادة',
    'زكيه حسن ساده',
    'انثى',
    70,
    'السبت ',
    '1\3\1445',
    '16\9\2023',
    'أ',
    6,
    93,
    'أ-6-93',
    NULL,
    NULL,
    'محمد رضا عبدالوهاب ال داؤود',
    'ابن',
    555887663,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    94,
    'بتول عبدالمحسن ال إبراهيم',
    'بتول عبدالمحسن ابراهيم',
    'انثى',
    99,
    'الاحد',
    '2\3\1445',
    '19\9\2023',
    'أ',
    6,
    94,
    'أ-6-94',
    NULL,
    NULL,
    'محمد فؤاد ال مدن',
    'ابن بتها',
    555589691,
    '4500014760'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    95,
    'مريم محمد حسين النشمي',
    'مريم محمد حسين نشمي',
    'انثى',
    74,
    'الخميس',
    '6\3\1445',
    '21\9\2023',
    'أ',
    6,
    95,
    'أ-6-95',
    NULL,
    NULL,
    'علي حسين المعيني',
    'ابن بتها',
    509888743,
    '4500015770'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    96,
    'بتول محمد حسن الشرفا',
    'بتول محمد حسن شرفا',
    'انثى',
    101,
    'الجمعة',
    '7\3\1445',
    '22\9\2023',
    'أ',
    6,
    96,
    'أ-6-96',
    NULL,
    NULL,
    'علوي سعود محمد الحسين ',
    'ابنها',
    563992099,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    97,
    'خديجة عبدالله ال إبراهيم',
    'خديجه عبدالله ابراهيم',
    'انثى',
    98,
    'السبت ',
    '8\3\1445',
    '23\9\2023',
    'أ',
    6,
    97,
    'أ-6-97',
    NULL,
    NULL,
    'حسن علي المحاسنة',
    'ابن',
    554026802,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    98,
    'زهراء خلف خلف المسري',
    'زهراء خلف خلف مسري',
    'انثى',
    67,
    'الاثنين',
    '10\3\1445',
    '25\9\2023',
    'أ',
    6,
    98,
    'أ-6-98',
    NULL,
    NULL,
    'خالد قاسم المعلم',
    'ابن عمها',
    5903817448,
    '4500016721'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    99,
    'عبدالله حسن ناصر ال داؤود',
    'عبدالله حسن ناصر داوود',
    'ذكر',
    73,
    'الأربعاء',
    '12\3\1445',
    '27\9\2023',
    'أ',
    6,
    99,
    'أ-6-99',
    NULL,
    NULL,
    'ايمن عبدالله حسن ال داؤود',
    'ابن',
    506806120,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    100,
    'علوية هاشم اسعد الصفواني',
    'علويه هاشم اسعد صفواني',
    'انثى',
    89,
    'الأربعاء',
    '12\3\1445',
    '27\9\2023',
    'أ',
    6,
    100,
    'أ-6-100',
    NULL,
    NULL,
    'نديم موسى علي السادة',
    'ابن',
    564469991,
    '4500017351'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    101,
    'بدور علي عبدالله البشري',
    'بدور علي عبدالله بشري',
    'انثى',
    44,
    'الاثنين',
    '10\3\1445',
    '25\9\2023',
    'أ',
    6,
    101,
    '249789',
    NULL,
    NULL,
    'احمد محمد علي العامر',
    'خالها',
    558106663,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    102,
    'حسين صالح حسن ال إبراهيم',
    'حسين صالح حسن ابراهيم',
    'ذكر',
    47,
    'السبت ',
    '15\3\1445',
    '30\9\2023',
    'أ',
    6,
    102,
    'أ-6-102',
    NULL,
    NULL,
    'احمد حسن ال إبراهيم',
    'عمه',
    559936618,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    103,
    'محمد حسين محمد الصادق',
    'محمد حسين محمد صادق',
    'ذكر',
    80,
    'الاحد',
    '16\3\1445',
    '1\10\2023',
    'أ',
    7,
    103,
    'أ-7-103',
    NULL,
    NULL,
    'علي محمد حسين الصادق',
    'ابن',
    552398500,
    '4500018352'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    104,
    'حسين علي صالح ال فريد',
    'حسين علي صالح فريد',
    'ذكر',
    19,
    'الاحد',
    '16\3\1445',
    '1\10\2023',
    'أ',
    7,
    104,
    'أ-7-104',
    NULL,
    NULL,
    'علي صالح ال فريد',
    'اب',
    548398277,
    '4500018402'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    105,
    'زهراء صالح حمزه التاروتي',
    'زهراء صالح حمزه تاروتي',
    'انثى',
    82,
    'الخميس',
    '27\3\1445',
    '12\10\2023',
    'أ',
    7,
    105,
    'أ-7-105',
    NULL,
    NULL,
    'صالح محمد صالح التاروتي',
    'ابنها',
    505853574,
    '4500021156'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    106,
    'صالح محمد صالح ال صلاح',
    'صالح محمد صالح صلاح',
    'ذكر',
    93,
    'الاثنين',
    '15\4\1445',
    '30\10\2023',
    'أ',
    7,
    106,
    'أ-7-106',
    NULL,
    NULL,
    'هلال صالح محمد ال صلاح',
    'ابنه',
    504911283,
    '4500025713'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    107,
    'فهيمة عبدالله العوامي',
    'فهيمه عبدالله عوامي',
    'انثى',
    72,
    'الاثنين',
    '29\4\1445',
    '13\11\2023',
    'أ',
    7,
    107,
    'أ-7-107',
    NULL,
    NULL,
    'سعيد حسين عباس ال رهين',
    'ابنها',
    536876305,
    '450029659'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    108,
    'زينب حسين علي مكي',
    'زينب حسين علي مكي',
    'انثى',
    17,
    'الجمعة',
    '3\5\1445',
    '17\11\2023',
    'أ',
    7,
    108,
    'أ-7-108',
    NULL,
    NULL,
    'ماجد علي هاشم مكي',
    'عمها',
    545240135,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    109,
    'فاطمة محمد حسين الغانم',
    'فاطمه محمد حسين غانم',
    'انثى',
    97,
    'الجمعة',
    '3\5\1445',
    '17\11\2023',
    'أ',
    7,
    109,
    'أ-7-109',
    NULL,
    NULL,
    'محمد سلمان علي ال داؤود',
    'ابنها',
    541730600,
    '4500030880'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    110,
    'مريم علي حسين العلكوم',
    'مريم علي حسين علكوم',
    'انثى',
    90,
    'الثلاثاء',
    '7\5\1445',
    '21\11\2023',
    'أ',
    7,
    110,
    'أ-7-110',
    NULL,
    NULL,
    'علي حسين محمد الخزعل',
    'مرة ابوه',
    505912383,
    '4500031770'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    111,
    'علي حسن علي المرهون',
    'علي حسن علي مرهون',
    'ذكر',
    59,
    'الثلاثاء',
    '7\5\1445',
    '21\11\2023',
    'أ',
    7,
    111,
    'أ-7-111',
    NULL,
    NULL,
    'حسين علي حسن المرهون',
    'ابنه',
    567247875,
    '4500031774'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    112,
    'محمد علي مهدي ال إسماعيل',
    'محمد علي مهدي اسماعيل',
    'ذكر',
    50,
    'الثلاثاء',
    '7\5\1445',
    '21\11\2023',
    'أ',
    7,
    112,
    'أ-7-112',
    NULL,
    NULL,
    'مفيد علي مهدي ال إسماعيل',
    'اخ',
    502030470,
    '4500031750'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    113,
    'فاطمة احمد إبراهيم العوامي',
    'فاطمه احمد ابراهيم عوامي',
    'انثى',
    61,
    'الاثنين',
    '20\5\1445',
    '4\12\2023',
    'أ',
    NULL,
    113,
    'أ-7-113',
    NULL,
    NULL,
    'احمد حبيب علي غلاب',
    'ابنها',
    540222733,
    '4500035478'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    114,
    'مكية علي حسين ال قريش',
    'مكيه علي حسين قريش',
    'انثى',
    69,
    'الأربعاء',
    '29\5\1445',
    '13\12\2023',
    'أ',
    7,
    114,
    'أ-7-114',
    NULL,
    NULL,
    'عادل علي محمد ال ضاعن',
    'ابنها',
    504833713,
    '4500038032'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    115,
    'محمد احمد حسن ال عبدالباقي',
    'محمد احمد حسن عبدالباقي',
    'ذكر',
    90,
    'السبت ',
    '10\6\1445',
    '23\12\2023',
    'أ',
    7,
    115,
    'أ-7-115',
    NULL,
    NULL,
    'علي محمد ال عبدالباقي',
    'ابنه',
    505822474,
    '4500041362'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    116,
    'رحمة سلمان حسن ال جعفر',
    'رحمه سلمان حسن جعفر',
    'انثى',
    82,
    'الاثنين',
    '12\6\1445',
    '25\12\2023',
    'أ',
    7,
    116,
    'أ-7-116',
    NULL,
    NULL,
    'حسن مرتضى عبدالله الهاشم',
    'زوجة عمه',
    542777817,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    117,
    'احمد علي مهدي ال معيوف',
    'احمد علي مهدي معيوف',
    'ذكر',
    64,
    'الخميس',
    '15\6\1445',
    '28\12\2023',
    'أ',
    7,
    117,
    'أ-7-117',
    NULL,
    NULL,
    'عبدالله علي مهدي المعيوف',
    'اخ',
    504821296,
    NULL
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    118,
    'أمنة علي عبدالله ال إبراهيم',
    'امنه علي عبدالله ابراهيم',
    'انثى',
    84,
    'الاحد',
    '18\6\1445',
    '31\12\2023',
    'أ',
    7,
    118,
    'أ-7-115',
    NULL,
    NULL,
    'حسين علي إبراهيم ال إبراهيم',
    'ابنها',
    557974250,
    '4500042929'
);
INSERT INTO graves (
    serial_number, name, normalized_name, gender, age,
    death_day, death_date_hijri, death_date_gregorian,
    section, row_number, grave_number, grave_reference,
    latitude, longitude,
    receiver_name, receiver_relationship, receiver_phone, report_number
) VALUES (
    119,
    'رجال 62               نساء 56',
    'رجال 62 نساء 56',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'أ',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
);