// Bundles the live web UI into app/www so the iOS app ships its OWN UI locally
// (App Store Guideline 4.2 safety + real offline shell). Data is still fetched
// live from the API via window.API_BASE (injected as /js/config.js below).
//
// IMPORTANT: the Android build uses server.url and does NOT run this script, so
// bundling only affects the iOS app. On the live website API_BASE is undefined
// (config.js is never served there) -> fetch paths stay relative -> no regression.

const fs = require('fs');
const path = require('path');

const APP_DIR = path.resolve(__dirname, '..');   // .../app
const ROOT = path.resolve(APP_DIR, '..');         // repo root
const WWW = path.join(APP_DIR, 'www');
const API_BASE = 'https://safwa-cemetery.com';

function ensure(p) { fs.mkdirSync(p, { recursive: true }); }

function copy(src, dest) {
    if (!fs.existsSync(src)) { console.warn('  ! missing (skipped):', path.relative(ROOT, src)); return; }
    ensure(path.dirname(dest));
    fs.copyFileSync(src, dest);
    console.log('  +', path.relative(WWW, dest));
}

// Inject the API-base config script right after the charset meta so it runs
// before any fetch/api() call. Idempotent.
function injectConfig(html) {
    if (html.includes('/js/config.js')) return html;
    const tag = '<script src="/js/config.js"></script>';
    if (html.includes('<meta charset="UTF-8">')) {
        return html.replace('<meta charset="UTF-8">', '<meta charset="UTF-8">\n' + tag);
    }
    return html.replace('<head>', '<head>\n' + tag);
}

console.log('Bundling web UI ->', path.relative(ROOT, WWW));
fs.rmSync(WWW, { recursive: true, force: true });
ensure(path.join(WWW, 'js'));
ensure(path.join(WWW, 'app'));

// 1) API base for the native bundle (empty/undefined on the website).
fs.writeFileSync(
    path.join(WWW, 'js', 'config.js'),
    `// Auto-generated by copy-web.js -- points the bundled native UI at the live API.\nwindow.API_BASE = '${API_BASE}';\n`
);
console.log('  + js/config.js  (API_BASE=' + API_BASE + ')');

// 2) HTML shells, with config.js injected.
fs.writeFileSync(path.join(WWW, 'index.html'),
    injectConfig(fs.readFileSync(path.join(APP_DIR, 'index.html'), 'utf8')));
console.log('  + index.html');
fs.writeFileSync(path.join(WWW, 'map.html'),
    injectConfig(fs.readFileSync(path.join(ROOT, 'map.html'), 'utf8')));
console.log('  + map.html');

// 3) Assets -- mirror the absolute paths the HTML references.
copy(path.join(ROOT, 'js', 'native-bridge.js'), path.join(WWW, 'js', 'native-bridge.js'));
copy(path.join(APP_DIR, 'app.css'), path.join(WWW, 'app', 'app.css'));

// 4) iOS-only density fixes. These are appended to the local native bundle so
// the TestFlight app feels like a compact phone app without changing web/Android.
const compactCssPath = path.join(APP_DIR, 'ios-compact.css');
if (fs.existsSync(compactCssPath)) {
    fs.appendFileSync(
        path.join(WWW, 'app', 'app.css'),
        '\n\n/* ===== iOS compact overrides ===== */\n' + fs.readFileSync(compactCssPath, 'utf8')
    );
    console.log('  + app/ios-compact.css (appended)');
}

['icon.svg', 'apple-touch-icon.png', 'manifest.json', 'icon-192.png', 'icon-512.png']
    .forEach(f => copy(path.join(ROOT, f), path.join(WWW, f)));

console.log('✓ Bundle ready in app/www');
